### ISSUE TITLE
Is it possible to limit the languages within the language detection

### ISSUE THREAD

**Issue by kormoczi** [snakers4/silero-vad#115]
Hi, I am tying to use the Language Classifier 95 model, but the accuracy is not so good.
I have tried to increase the top_n value, but did not help too much.
I thought I can neglect most of the languages (which I do not care about) with specifying a reduced set of languages in the lang_dict and the lang_group_dict parameters in the following line:
`languages, language_groups = get_language_and_group(wav, model, lang_dict, lang_group_dict, top_n=2)`
but it does not work.
Is it possible somehow to specify a subset of the languages for this model?
Thanks!

**Comment by snakers4** [comment]
Hi,

> Hi, I am tying to use the Language Classifier 95 model, but the accuracy is not so good.

Can you describe your validation dataset, its size and composition, maybe share some metrics (accuracy, precision, recall)?

> Is it possible somehow to specify a subset of the languages for this model?

You can just rewrite this function - https://github.com/snakers4/silero-vad/blob/master/utils_vad.py#L339-L362

**Comment by kormoczi** [comment]
Hi,
I do not have a validation dataset yet, we are just speaking short sentences into the microphone...
But I will try to setup some repeatable tests and share some metrics with you soon.
On the other hand, I will check this function in the utils_vad.py.
Thanks!
