### ISSUE TITLE
Kindly look into this issue and provide me example on how to do the inference on ONNX Model with live audio streaming

### ISSUE THREAD

**Issue by KeyanatGiggso** [snakers4/silero-vad#123]
this is the Code 

import io
import numpy as np
import torch
torch.set_num_threads(1)
import torchaudio
import matplotlib
import matplotlib.pylab as plt
torchaudio.set_audio_backend("soundfile")
import pyaudio

model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_vad',
                              force_reload=True)

(get_speech_ts,
 get_speech_ts_adaptive,
 save_audio,
 read_audio,
 state_generator,
 single_audio_stream,
 collect_chunks) = utils

**def init_onnx_model(model_path: str):
    return onnxruntime.InferenceSession(model_path)
    
model = init_onnx_model(model_path='./model.onnx')**

**def validate(model,inputs: torch.Tensor):
    with torch.no_grad():
        ort_inputs = {'input': inputs.cpu().numpy()}
        outs = model.run(None, ort_inputs)
        outs = [torch.Tensor(x) for x in outs]
    return outs[0]**

def int2float(sound):
    abs_max = np.abs(sound).max()
    sound = sound.astype('float32')
    if abs_max > 0:
        sound *= 1/abs_max
    sound = sound.squeeze() 
    return sound

FORMAT = pyaudio.paInt16
CHANNELS = 1
SAMPLE_RATE = 16000
CHUNK = int(SAMPLE_RATE / 10)

audio = pyaudio.PyAudio()
stream = audio.open(format=FORMAT,
                    channels=CHANNELS,
                    rate=SAMPLE_RATE,
                    input=True,
                    frames_per_buffer=CHUNK)
data = []
voiced_confidences = []

print("Started Recording")
for i in range(0, frames_to_record):
    
    audio_chunk = stream.read(int(SAMPLE_RATE * frame_duration_ms / 1000.0))
    
    # in case you want to save the audio later
    data.append(audio_chunk)
    
    audio_int16 = np.frombuffer(audio_chunk, np.int16);

    audio_float32 = int2float(audio_int16)
    
    # get the confidences and add them to the list to plot them later
    vad_outs = validate(model, torch.from_numpy(audio_float32))
    # only keep the confidence for the speech
    voiced_confidences.append(vad_outs[:,1])
    
print("Stopped the recording")

# plot the confidences for the speech
plt.figure(figsize=(20,6))
plt.plot(voiced_confidences)
plt.show()

The Error I'm getting is,

vad_outs1 = validate(model, torch.from_numpy(audio_int161))
Traceback (most recent call last):
  File "testimport.py", line 76, in <module>
    vad_outs1 = validate(model, torch.from_numpy(audio_int161))
  File "testimport.py", line 47, in validate
    outs = model.run(None, ort_inputs)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIsEE) , expected: (N11onnxruntime17PrimitiveDataTypeIfEE)

@snakers4 Kindly provide me the solution

**Comment by snakers4** [comment]
Hi,

I cannot replicate the example exactly because I have no desktop PC where pyaudio can be installed.

But judging from this minimal example:

```
num_samples = 4000
wav = read_audio(f'{files_dir}/en.wav')
wav_chunks = iter([wav[i:i+num_samples] for i in range(0, len(wav), num_samples)])

for chunk in wav_chunks:
  assert chunk.dtype == torch.float32
  _ = validate_onnx(model, chunk.unsqueeze(0)) # had to add unqueeze here
```

And this line from our iterator example - https://github.com/snakers4/silero-vad/blob/master/utils_vad.py#L606-L608, the ONNX model likely accepts batched data.

In any case, all of this is not really relevant, because in a few days we will be updating the models, radically simplifying all of the examples, removing the iterators, decreasing the chunk size to 30ms and most likely deprecating all of the ONNX models.

**Comment by snakers4** [comment]
We decided to deprecate the ONNX models for the time being.
The new release will be published shortly.
So this is kind of obsolete.
