### ISSUE TITLE
Migrating examples to new models

### ISSUE THREAD

**Issue by snakers4** [snakers4/silero-vad#124]
@Kai-Karren @Bontempogianpaolo1 

In a few days we will be radically changing the models:

- Probably dropping ONNX VAD models (we have not decided yet);
- Reducing chunk size to 30ms (chunk will be flexible, but larger than 30ms);
- Removing separate 8 / 16 kHz models, now all models would work with 8 and 16 kHz;
- Most likely deprecating micro, mini and ordinary models in favor of just a mini-sized models (still running last experiments);
- New models will be compatible with mobile builds of PyTorch;
- Dropping the batched buffering approach we used because of large chunks;

i.e. radically simplifying and speeding up the models.

You have contributed to the [examples](https://github.com/snakers4/silero-vad/tree/master/examples), would you like to participate in improving them using the new models?

**Comment by Kai-Karren** [comment]
This sounds indeed like radical changes and lots of work that has been done.
Yes, I think I could participate in updating the examples 😄

**Comment by snakers4** [comment]
Nice, many thanks

**Comment by adamnsandle** [comment]
Updated `pyaudio-streaming-examples.ipynb` to work with the new model

**Comment by snakers4** [comment]
New release has been made
