### ISSUE TITLE
can't use v2.0-legacy❓ Questions / Help / Support

### ISSUE THREAD

**Issue by IamSVP94** [snakers4/silero-vad#147]
I can't use special version (for example ```snakers4/silero-vad:v2.0-legacy```) from torchhub , because there is incorrect name in ```hubconf.py```
Now:
```
snakers4_silero-vad_master
```
Correct for using:
```
snakers4_silero-vad_v2.0-legacy
```
Can I help you with that easy issue?

**Comment by snakers4** [comment]
@IamSVP94 

Can you maybe please update to the latest model?

**Comment by IamSVP94** [comment]
The reason for using legacy version is old torch (0.7) I can't use new release

**Comment by snakers4** [comment]
I remember `torch.hub` being introduced in 1.7, I believe this repo started with 1.6 and then migrated to 1.7. 0.7 was several years ago.

> I can't use special version (for example snakers4/silero-vad:v2.0-legacy) from torchhub , because there is incorrect name in hubconf.py

So you check out the repo using this tag `v2.0-legacy` or are trying to load it via torch hub directly somehow?

**Comment by IamSVP94** [comment]
I am trying ```torch.hub.load(repo_or_dir='snakers4_silero-vad_v2.0-legacy', model='silero_vad')```

**Comment by snakers4** [comment]
I believe the error comes from this line in the code:

```
model = init_jit_model(model_path=f'{hub_dir}/snakers4_silero-vad_master/files/model.jit')
```

I am not sure that rewriting git history for such use cases would be a good idea, but a quick and dirty fix is:

```
!mv /root/.cache/torch/hub/snakers4_silero-vad_v2.0-legacy/ /root/.cache/torch/hub/snakers4_silero-vad_master/
model, utils = torch.hub.load(repo_or_dir='/root/.cache/torch/hub/snakers4_silero-vad_master/',
                              model='silero_vad',
                              source='local')
```

In retrospect, probably we should have used [this](https://github.com/snakers4/silero-models/blob/master/hubconf.py#L22) instead of [this](https://github.com/snakers4/silero-vad/blob/master/hubconf.py#L23-L27)

**Comment by IamSVP94** [comment]
I already use dirty fix) I just tried to help improve this brilliant repo) The same problem will appear in the future

**Comment by IamSVP94** [comment]
I use this fix in `hubconf.py`
```
CACHE_DIR = 'snakers4/silero-vad:v2.0-legacy'

model = init_jit_model(model_path=f'{hub_dir}/{CACHE_DIR}/files/model.jit')
```

**Comment by snakers4** [comment]
Many thanks for you interest and support
