### ISSUE TITLE
New Features Poll

### ISSUE THREAD

**Issue by snakers4** [snakers4/silero-vad#150]
Thinking about new features, medium term:

[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Higher%20accuracy)](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Higher%20accuracy/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Python%20packages)](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Python%20packages/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/8k%20support%20for%20ONNX)](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/8k%20support%20for%20ONNX/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Higher%20performance)](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Higher%20performance/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Wake%20word%20detection%20models)](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Wake%20word%20detection%20models/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Other%20model%20formats%20(please%20comment))](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Other%20model%20formats%20(please%20comment)/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Music%20detection%20for%20longer%20utterances%20(several%20seconds))](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Music%20detection%20for%20longer%20utterances%20(several%20seconds)/vote)
[![](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Audio%20event%20classification%20for%20longer%20utterances%20(several%20seconds))](https://api.gh-polls.com/poll/01FRHQ0TATC7CTV8ES2SKA1RKW/Audio%20event%20classification%20for%20longer%20utterances%20(several%20seconds)/vote)

**Comment by snakers4** [comment]
You can give 1 vote per each item, i.e. multiple vote

**Comment by snakers4** [comment]
The results are surprising

**Comment by seekingdeep** [comment]
perhaps export VAD model to C++ or .py
so it wont require any dependencies to install
