### ISSUE TITLE
max_speech_duration [Suggestion]

### ISSUE THREAD

**Issue by seekingdeep** [snakers4/silero-vad#155]
Hi there,
in the case that the default hyper-parameters result in a long speech duration, a good suggestion would to to add the parameter of `max_speech_duration (ms)`

example:
The result of detection and merger results in a 17 seconds speech, when setting `max_speech_duration= 9000`
then the first 9 seconds of time-stamps will be considered a single sentence, and starting from the next detected time-stamp will be merged with the remainder time-stamps, with rule of not exceeding the maximum duration.

**Comment by snakers4** [comment]
Hi,

We had requests like that, but despite of being trivial to implement on the surface all of them seem a bit too arbitrary.

If an utterance is longer that N seconds, it is not correct to split it arbitrarily, i.e. make an unjustified split. For example you may split a word in half.

Basically this can be solved with one short for loop, but that is reserved for a user. We also do such splits in a more correct fashion in our enterprise software, but this is out of scope here.

**Comment by seekingdeep** [comment]
> Basically this can be solved with one short for loop

The for loop task will be to do what exactly?
