### ISSUE TITLE
Last sample does not check min_speech_duration_ms

### ISSUE THREAD

**Issue by gabrielziegler3** [snakers4/silero-vad#169]
## 🐛 Bug

The attribute `min_speech_duration_ms` is not applied to the last chunk of speech in variable `speeches` in [utils_vad.py](https://github.com/gabrielziegler3/silero-vad/blob/76687cbe25ffdf992ad824a36bfe73f6ae1afe72/utils_vad.py#L242).

## To Reproduce

I can't provide the signal that produced this bug, but it should not be hard to see why it is happening.
Run the function `get_speech_timestamps` passing an audio that has the last speech activity with length < `min_speech_duration_ms`. 
This results in the last chunk of code having the same start and end when using `return_seconds = True`, e.g:
```python
[{"start": 1.4, "end": 5.2},
{"start": 8.4, "end": 9.0},
{"start": 10.2, "end": 10.2}]
```
## Expected behavior

The last chunk should be checked and then removed since `end - start < min_speech_duration_ms`, hence the output should be:

```python
[{"start": 1.4, "end": 5.2},
{"start": 8.4, "end": 9.0}]
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0 
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): 
 - Python version: python 3.8
 - CUDA/cuDNN version: No CUDA
 - GPU models and configuration: - 
 - Any other relevant information: -

**Comment by snakers4** [comment]
My colleague will take a look shortly (it is his function).
Let's discuss in the PR, if necessary.

**Comment by snakers4** [comment]
Many thanks for your interest, time and attention
