### ISSUE TITLE
silero_vad.jit Unknown type name 'NoneType':

### ISSUE THREAD

**Issue by wwxm0523** [snakers4/silero-vad#178]
model=init_jit_model(model_path='silero_vad.jit')
  File "/Users/miniconda3/lib/python3.9/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
RuntimeError: 
Unknown type name 'NoneType':
Serialized   File "code/__torch__/torch/nn/modules/conv.py", line 7
  bias : Optional[Tensor]
  training : bool
  _is_full_backward_hook : NoneType
                           ~~~~~~~~ <--- HERE
  transposed : bool
  _reversed_padding_repeated_twice : List[int]

**Comment by snakers4** [comment]
Which PyTorch version do you have?

**Comment by snakers4** [comment]
Most likely caused by an older PyTorch version.
Since there was no response, closing the issue.
