### ISSUE TITLE
8000Hz ONNX model❓ Questions / Help / Support

### ISSUE THREAD

**Issue by nicolaspanel** [snakers4/silero-vad#186]
First, congratulations for your work and for sharing it with the community !!

https://github.com/snakers4/silero-vad/releases/tag/v3.1 indicates
> Only 16kHz available now (ONNX has some issues with if-statements and / or tracing vs scripting) with cryptic errors;

Do you think there will be some progress on that soon ?

Best regards

**Comment by snakers4** [comment]
Hi,

No ETA on this one

**Comment by adamnsandle** [comment]
@nicolaspanel 
Latest ONNX version (v4) supports both 8k and 16k sampling rates as well as batching.
https://github.com/snakers4/silero-vad/wiki/Version-history-and-Available-Models

**Comment by snakers4** [comment]
Please open new issues if something does not work with 8k ONNX
