### ISSUE TITLE
Finetuning VAD model

### ISSUE THREAD

**Issue by vlajnaya-mol** [snakers4/silero-vad#19]
Is there a way to finetune provided pretrained model on my own data? Can you share some code for training? Thanks!

**Comment by snakers4** [comment]
Hi,

Our end-goal with `silero-vad` is to provide a dependable, working and generalizable solution, not a toolkit.
Though in some simple cases (i.e. adding a some very different language) a one-vs-all classifier can just be trained on a pre-trained network.

So, the main question is, which case do you have in mind? Maybe we can just cover it in the future releases.

**Comment by snakers4** [comment]
If you would like to fit the VAD on Ukrainian, then most likely the VAD would work with it OOTB and we may add official support later.

**Comment by elsobhano** [comment]
> If you would like to fit the VAD on Ukrainian, then most likely the VAD would work with it OOTB and we may add official support later.

So, Is it impossible to fine-tune your model(Silero-VAD) on a custom dataset?

**Comment by weimeng23** [comment]
> > If you would like to fit the VAD on Ukrainian, then most likely the VAD would work with it OOTB and we may add official support later.
> 
> So, Is it impossible to fine-tune your model(Silero-VAD) on a custom dataset?

+1, some question

**Comment by AvoyDatta** [comment]
> > > If you would like to fit the VAD on Ukrainian, then most likely the VAD would work with it OOTB and we may add official support later.
> > 
> > 
> > So, Is it impossible to fine-tune your model(Silero-VAD) on a custom dataset?
> 
> +1, some question

+1, same question

in my use-case, I would need the VAD to selectively ignore background voices - something it currently does a rather poor job at. Have a labeled dataset for this.

**Comment by Anna-Pinewood** [comment]
Is there any code example here? I also would like to tune vad model on specific language...

**Comment by snakers4** [comment]
As a first step - we released the dataset - https://github.com/snakers4/silero-vad/tree/master/datasets
