### ISSUE TITLE
Certificate error on  model download using the torch hub (expired certificates)

### ISSUE THREAD

**Issue by saman-rahbar** [snakers4/silero-vad#197]
## To Reproduce

1. Torch.hub (download  from repo dir: 'snakers4/silero-vad', model='slier_lang_detector')

## Environment

 - PyTorch Version = 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8.6

**Comment by snakers4** [comment]
Does using a newer PyTorch version help?

> slier_lang_detector

The correct invocation is

```
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_lang_detector',
                              force_reload=True,
                              onnx=USE_ONNX)
```

**Comment by saman-rahbar** [comment]
Unfortunately no! With the latest version of PyTorch the same issue persists (with the invocation you mentioned)!

**Comment by snakers4** [comment]
Can you post a minimal reproduction script?

**Comment by saman-rahbar** [comment]
> Can you post a minimal reproduction script?
Just tested a few minutes ago and it seems to be working fine now!! Strange! Thanks for the quick support @snakers4
