### ISSUE TITLE
Model detects wind as speech

### ISSUE THREAD

**Issue by wciurzynski** [snakers4/silero-vad#200]
Model detects speech for window_size_samples smaller than 768 with ONXX=False.
I process this sound with window_size_samples 256 and threshold 0.2 for phone calls. Maybe
the accuracy of the model would be higher if I would use model for Polish language :)
I cannot set threshold to 0.9 because often even 0.5 is too high for phone calls.

Could you check this sound of wind and train model so that wind would be not detected as speech ?
[wind phone call.zip](https://github.com/snakers4/silero-vad/files/8825634/wind.phone.call.zip)

**Comment by snakers4** [comment]
Tweaking `threshold` and `min_speech_duration_ms`, as well as `window_size_samples` for each domain is a good idea.

For this particular audio the chart looks like this, so setting a threshold of 0.8+ would solve the issue.

![image](https://user-images.githubusercontent.com/12515440/171797319-1de6b738-2772-41e2-b03b-94b4ff845494.png)

For some particular languages - I do not believe that we have the resources to tweak quality in the public free version.

As for wind noises, we will make sure to add more wind noises into our noise database when / if we will be updating the model.
