### ISSUE TITLE
A memory leak occurred while using the Jit model

### ISSUE THREAD

**Issue by yangrz7** [snakers4/silero-vad#240]
## To Reproduce

1. Loading Jit model
2. Inference Model
3. Memory leak

```
self.model = init_jit_model('./asr/silero_vad.jit')
self.model(torch.from_numpy(data), 16000).item()
```
But When I switched to the ONNX model, the problem did not appear again

## Environment

Please copy and paste the output from this 
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

 - PyTorch Version (e.g., 1.0):1.9.0
 - OS (e.g., Linux):MacOS 12.5.1
 - How you installed PyTorch (`conda`, `pip`, source):conda
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:no
 - GPU models and configuration:no
 - Any other relevant information:

**Comment by snakers4** [comment]
Hi,

https://github.com/snakers4/silero-vad/discussions/232
