### ISSUE TITLE
Prevent tons of errors while using with onnxruntime-gpu

### ISSUE THREAD

**Issue by owlsometech-kenyang** [snakers4/silero-vad#243]
Hi, I am using this fantastic project with onnxruntime on my Jetson Nano (ARM v8) which runs pretty well. But for some reason, I have to use onnxruntime-gpu 1.6.0 on it since now. 
After that,  onnxruntime-gpu throws a lot of errors because it try to use Nano’s GPU which didn’t work and try to fallback to CPU but still not working for some reason.
![Screenshot from 2022-09-26 12-59-04](https://user-images.githubusercontent.com/50938258/194930165-70638d7e-53fc-4081-b273-d7ca0d6b79f7.png) 
The workaround I have tried is to set cpu provider for onnxruntime-gpu like below.
```python
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                                      model='silero_vad',
                                      force_reload=False,
                                      onnx=True)
model.session.set_providers(['CPUExecutionProvider']) 
(get_speech_timestamps,
         save_audio,
         read_audio,
         VADIterator,
         collect_chunks) = utils
self.vad_iterator = VADIterator(model)
```
Although it works, it still can’t prevent those errors showing on my screen.
So I am wondering if we can have new parameter like `force_cpu` or something to set provider before we create onnxruntime session in OnnxWrapper.
```python
class OnnxWrapper():

    def __init__(self, path, force_cpu=False):
        import numpy as np
        global np
        import onnxruntime
        if force_cpu:
            self.session = onnxruntime.InferenceSession(
                path, providers=['CPUExecutionProvider'])
        else:
            self.session = onnxruntime.InferenceSession(path)
```
That is my first thought. Any more elegant way to get rid of those errors are appreciated, thanks.

**Comment by snakers4** [comment]
> Hi, I am using this fantastic project with onnxruntime on my Jetson Nano (ARM v8) which runs pretty well. But for some reason, I have to use onnxruntime-gpu 1.6.0 on it since now.
> After that, onnxruntime-gpu throws a lot of errors because it try to use Nano’s GPU which didn’t work and try to fallback to CPU but still not working for some reason.

This is not supposed to run on GPU at all (especially with ONNX!). 
We did not test on GPU with ONNX.

> So I am wondering if we can have new parameter like force_cpu or something to set provider before we create onnxruntime session in OnnxWrapper.

Can you probably just override our `class OnnxWrapper():` and see if it resolves your problem with these pesky errors, and if so, push a PR?
It is quite unlikely that we will have time / focus soon to test the VAD with GPU via ONNX.

**Comment by owlsometech-kenyang** [comment]
sure! I will push a PR soon after I tested it.

**Comment by snakers4** [comment]
Discussion in the PR
