### ISSUE TITLE
Bug report - Demo notebook with error on Stream imitation example

### ISSUE THREAD

**Issue by hobojoe** [snakers4/silero-vad#249]
## 🐛 Bug

While following the demo notebook(https://colab.research.google.com/github/snakers4/silero-vad/blob/master/silero-vad.ipynb#scrollTo=iDKQbVr8jsry), I get an error on the **Stream imitation example**.

`ValueError: only one element tensors can be converted to Python scalars`
![image](https://user-images.githubusercontent.com/1886514/198322684-7b950142-03ff-43a3-a7f3-6f555f25c612.png)

## To Reproduce

1. Open demo notebook
2. Run Install Dependencies
3. Run Stream imitation example

## Expected behavior

Successful execution of the notebook
## Environment

Please copy and paste the output from this 
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by snakers4** [comment]
confirmed

**Comment by adamnsandle** [comment]
@hobojoe 
Hotfixed. Thanks for reporting!
