### ISSUE TITLE
non-ONNX version of new VAD model doesn't work with 8 kHz audio

### ISSUE THREAD

**Issue by khusainovaidar** [snakers4/silero-vad#250]
New version of VAD non-ONNX model doesn't work with 8 kHz audio. 
Code from example:

SAMPLING_RATE = 8000
USE_ONNX = False
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_vad',
                              force_reload=True,
                              onnx=USE_ONNX)

(get_speech_timestamps,
 save_audio,
 read_audio,
 VADIterator,
 collect_chunks) = utils

wav = read_audio('any_8k_audio_file.wav', sampling_rate=SAMPLING_RATE)
speech_timestamps = get_speech_timestamps(wav, model, sampling_rate=SAMPLING_RATE)

ValueError: only one element tensors can be converted to Python scalars
on line 252 of utils_vad: speech_prob = model(chunk, sampling_rate).item()

**Comment by khusainovaidar** [comment]
for my example model returns dim 3 tensor and it kills it on item()

**Comment by khusainovaidar** [comment]
Plus maybe it's not quite the same issue, but we found (subjectively) quality degradation of new version of VAD (ONNX version). We tested it on clear samples and it skips lots of voiced segments now. At the same time previous version works excellent.

**Comment by snakers4** [comment]
> 'any_8k_audio_file.wav',

Please provide your audio file.
