### ISSUE TITLE
【Help】 Error occurred while executing torch.hub.load

### ISSUE THREAD

**Issue by hstensor** [snakers4/silero-vad#252]
## ❓ Questions and Help
While following the demo notebook
https://colab.research.google.com/github/snakers4/silero-vad/blob/master/silero-vad.ipynb#scrollTo=pSifus5IilRp

And I wanted to use a lowered torch version, so I lowered it to 1.9.0.
Then I get an error while executing torch.hub.load.
This torch version has worked fine until now...

## Error log
I could not see the error details on colab. So I share the error text on another PC (ubuntu)

1666841474879,terminate called after throwing an instance of 'c10::Error'
1666841474879,"  what():  isTuple()INTERNAL ASSERT FAILED at ""/pytorch/aten/src/ATen/core/ivalue_inl.h"":1306, please report a bug to PyTorch. Expected Tuple but got String"
1666841474879,Exception raised from toTuple at /pytorch/aten/src/ATen/core/ivalue_inl.h:1306 (most recent call first):
1666841474879,"frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4342e37a22 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)"
1666841474879,"frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f4342e343db in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)"
1666841474879,"frame #2: c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::string const&) + 0x3e (0x7f4342e348ce in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)"
1666841474879,frame #3: <unknown function> + 0x38c8fa7 (0x7f4389081fa7 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
1666841474879,frame #4: <unknown function> + 0x38ca045 (0x7f4389083045 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
1666841474879,frame #5: torch::jit::SourceRange::highlight(std::ostream&) const + 0x36 (0x7f438675c086 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
1666841474879,frame #6: torch::jit::ErrorReport::what() const + 0x2c5 (0x7f438673ce45 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
1666841474879,frame #7: <unknown function> + 0x4f4eee (0x7f439945ceee in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
1666841474879,frame #8: <unknown function> + 0x502e0a (0x7f439946ae0a in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)

## To Reproduce

Open demo notebook
Run Install Dependencies
・torch==1.9.0
・torchaudio==0.9.0

Run torch.hub.load

## Environment
Google Colab
torch==1.9.0
torchaudio==0.9.0

I look forward to hearing from you. ♡

**Comment by snakers4** [comment]
Hi, older torch versions are not supported. Please try 1.11 or newer or ONNX.

**Comment by hstensor** [comment]
It solved. Thanks for your support.
