### ISSUE TITLE
get_speech_timestamps error

### ISSUE THREAD

**Issue by xlkness** [snakers4/silero-vad#260]
python version:3.7
libs: torch==1.12.0 torchaudio==0.12.0

========================================

speech_timestamps = get_speech_timestamps(raw_frames, model1, sampling_rate=sample_rate)
  File "vad\silerovad_utils.py", line 241, in get_speech_timestamps
    speech_prob = model(chunk, sampling_rate).item()
  File "G:\work\python\audio_env\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/vad/model/vad_annotator.py", line 43, in forward
      _h = self._h
      _c = self._c
      out0, _6, _7, = (_model).forward(x0, _h, _c, )
                       ~~~~~~~~~~~~~~~ <--- HERE
      self._h = _6
      self._c = _7
  File "code/__torch__/vad/model/vad_annotator/___torch_mangle_28.py", line 26, in forward
    x3 = (encoder).forward(x2, )
    decoder = self.decoder
    x4, h0, c0, = (decoder).forward(x3, h, c, )
                   ~~~~~~~~~~~~~~~~ <--- HERE
    _0 = torch.mean(torch.squeeze(x4, 1), [1])
    out = torch.unsqueeze(_0, 1)
  File "code/__torch__/vad/model/vad_annotator.py", line 150, in forward
    else:
      rnn0 = self.rnn
      _26 = (rnn0).forward__0(torch.permute(x, [0, 2, 1]), None, )
             ~~~~~~~~~~~~~~~~ <--- HERE
      x2, _27, = _26
      h2, c2, = _27
  File "code/__torch__/torch/nn/modules/rnn.py", line 80, in forward__0
    training = self.training
    _13, _14, = hx0
    _15, _16, _17 = torch.lstm(input0, [_13, _14], _flat_weights, True, 2, 0.10000000000000001, training, False, True)
                    ~~~~~~~~~~ <--- HERE
    hidden = (_16, _17)
    if torch.__not__(is_batched):

Traceback of TorchScript, original code (most recent call last):
  File "/home/keras/notebook/nvme_raid/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 377, in forward

        if sr == 16000:
            out, self._h, self._c = self._model(x, self._h, self._c)
                                    ~~~~~~~~~~~ <--- HERE
        elif sr == 8000:
            out, self._h, self._c = self._model_8k(x, self._h, self._c)
  File "/home/keras/notebook/nvme_raid/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 300, in forward
        x = self.encoder(x)

        x, h, c = self.decoder(x, h, c)
                  ~~~~~~~~~~~~ <--- HERE

        out = x.squeeze(1).mean(dim=1).unsqueeze(1)
  File "/home/keras/notebook/nvme_raid/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 237, in forward
            x, (h, c) = self.rnn(x.permute(0, 2, 1), (h, c))
        else:
            x, (h, c) = self.rnn(x.permute(0, 2, 1))
                        ~~~~~~~~ <--- HERE

        x = x.permute(0, 2, 1)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 769, in forward__0
        self.check_forward_args(input, hx, batch_sizes)
        if batch_sizes is None:
            result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
                     ~~~~~~~~ <--- HERE
                              self.dropout, self.training, self.bidirectional, self.batch_first)
        else:
RuntimeError: The expanded size of the tensor (256) must match the existing size (64) at non-singleton dimension 1.  Target sizes: [1, 256].  Tensor sizes: [256, 64]

**Comment by adamnsandle** [comment]
Could you upload the audio causing this error?

**Comment by xlkness** [comment]
It's a normal wav audio with 16000 sample rate. My code looks like this:
```
torchaudio.set_audio_backend("soundfile")
model, utils = torch.hub.load(repo_or_dir='vad',model='silero_vad',source='local', onnx=False)
speech_timestamps = get_speech_timestamps(raw_frames, model, sampling_rate=sample_rate, min_speech_duration_ms=100)
```
The `vad` directory holds `silero_vad.jit`.

**Comment by adamnsandle** [comment]
does this error occur when you load model using the following code?
```
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                                                model='silero_vad',
                                                force_reload=True,
                                                onnx=False)
```

**Comment by xlkness** [comment]
yep! And I tested many wav files and they were all  wrong. The error is exactly the same as `source='load'`

> does this error still occur when you load model using the following code?
> 
> ```
> model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
>                                                 model='silero_vad',
>                                                 force_reload=True,
>                                                 onnx=False)
> ```

**Comment by xlkness** [comment]
But the older version before 3 days ago works will with python 3.6 and torch 1.10

**Comment by adamnsandle** [comment]
I can't reproduce the error. This code works fine both locally and on the Google Collab using different audio files:
```
import torch
import torchaudio
torch.set_num_threads(1)
SAMPLING_RATE = 16000
USE_ONNX = False

torchaudio.set_audio_backend("soundfile")
torch.hub.download_url_to_file('https://models.silero.ai/vad_models/en.wav', 'en_example.wav')

model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
model='silero_vad',
force_reload=True,
onnx=USE_ONNX)

(get_speech_timestamps,
 save_audio,
 read_audio,
 VADIterator,
 collect_chunks) = utils

wav = read_audio('test.wav')
speech_timestamps = get_speech_timestamps(wav, model, sampling_rate=SAMPLING_RATE, min_speech_duration_ms=100, visualize_probs=True)
 ```

**Comment by xlkness** [comment]
thanks a lot! I'm gonna have to do some more debugging.

**Comment by snakers4** [comment]
@xlkness 
one way to approach this is to try standard pre-built pytorch docker images
and see if it replicates there
if it does not, then 99% chance is that the problem is with your installation of pytorch

**Comment by xlkness** [comment]
> @xlkness one way to approach this is to try standard pre-built pytorch docker images and see if it replicates there if it does not, then 99% chance is that the problem is with your installation of pytorch

thanks very much!! It's my fault.Because i load model and use it in multithreaded env.

**Comment by snakers4** [comment]
Please make sure to **_disable gradients in each of your threads_**, or horrible things may happen.
Or use ONNX.

**Comment by xlkness** [comment]
ok, I'll check it.thanks again.
