### ISSUE TITLE
Bug report - loading the latest onnx model encounter ONNXRuntimeError

### ISSUE THREAD

**Issue by owlsometech-kenyang** [snakers4/silero-vad#262]
## 🐛 Bug

While i was using the latest onnx model with `onnxruntime-gpu v1.6.0` , I encountered the ONNXRuntimeError like below:
![onnxruntime-gpuv1 6 0](https://user-images.githubusercontent.com/50938258/199017283-9a957425-6ff2-4023-93c4-261eb16ca731.png), it happened as well with `onnxruntime v1.6.0`
Also I tested `onnxruntime v1.10.0`, then it shows another error:
![onnxruntimev1 10 0](https://user-images.githubusercontent.com/50938258/199017543-b3a88b12-f3d2-4e8d-8cfd-44558b51c9a7.png)
But when I rollback to previous version , it works.
I am wondering if there is any missing info from building onnx model, or do I need to change to the specific version of onnxruntime?

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux for Tegra
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): source
 - Python version: 3.6.9
 - CUDA/cuDNN version: x
 - GPU models and configuration: x
 - Any other relevant information: x

**Comment by adamnsandle** [comment]
All tests were held using onnxruntime 1.13.1
For some reason versions < 1.11 can't load new models.

**Comment by owlsometech-kenyang** [comment]
Thanks for reply, i will see if I can update to 1.13.1 on my device.
