### ISSUE TITLE
❓ Support : Maximum performance guidance

### ISSUE THREAD

**Issue by tomschelsen** [snakers4/silero-vad#287]
[Performance metrics](https://github.com/snakers4/silero-vad/wiki/Performance-Metrics) provides performance using 1 thread and batch size equal to 1, which is totally fine for a benchmark, but as a fresh new user I am having difficulties understanding how I could get maximum performance (use case : run the VAD on dozens of thousands of recorded audio files, having high core counts machines for that), apart from using ONNX instead of JIT.

Should I set `session.intra_op_num_thread`s and `session.inter_op_num_threads ` to the number of cores I have available, and maybe more importantly how do I set the batch size after torch.hub.loading the model/utils ?

Adding an example in that direction in the wiki/notebook would be great.

Thanks a lot

**Comment by snakers4** [comment]
> run the VAD on dozens of thousands of recorded audio files, having high core counts machines for that

Hi, our VAD was not designed for this purpose.

**Comment by tomschelsen** [comment]
I do understand that it is for streaming first, and I do have a streaming use case coming later on, so I would still like to know the expected effect of changing num_threads to something different than 1, and how to change the batch size without forking the source code if that is possible. Thanks
