### ISSUE TITLE
How to compile a C++ demo in a Windows environment？

### ISSUE THREAD

**Issue by 1311004771** [snakers4/silero-vad#304]
How to compile a C++ demo in a Windows environment？
I changed the onnxruntime of the linux version to the win version and the compilation did not pass, ask for help, thanks

**Comment by snakers4** [comment]
Probably a queation for onnx runtime maintainers.

**Comment by 1311004771** [comment]
At compile time, the main thing is the operation error of ORT.
I don't know what to do with it, do you have any good suggestions

**Comment by garymmi** [comment]
hi all
the correct way to compile inference code with onnxruntime lib 
`#ifdef _MSC_VER
        session = std::make_shared<Ort::Session>(
                            env_, ToWString(model_path).c_str(), session_options);
#else                
        session = std::make_shared<Ort::Session>(env, model_path.c_str(), session_options);
#endif        
    }

#ifdef _MSC_VER
std::wstring ToWString(const std::string& str) {
  unsigned len = str.size() * 2;
  setlocale(LC_CTYPE, "");
  wchar_t* p = new wchar_t[len];
  mbstowcs(p, str.c_str(), len);
  std::wstring wstr(p);
  delete[] p;
  return wstr;
}
#endif
`
