### ISSUE TITLE
Bug report - [X]cpp example

### ISSUE THREAD

**Issue by shine-xia** [snakers4/silero-vad#315]
in file examples/cpp/silero-vad-onnx.cpp, line 124
Do you mean "if (temp_end == 0)" ?
Otherwise temp_end will never get non-zero values

**Comment by yuGAN6** [comment]
Thanks for the report! You are right on that. 
It should be `if (temp_end == 0)` correspond to line 506 `if not self.temp_end` in utils_vad.py.  You can create a pull request to fix.

**Comment by snakers4** [comment]
Newer ticket for cpp example bug tracking - https://github.com/snakers4/silero-vad/issues/315
A community PR would be appreciated to update the example
