### ISSUE TITLE
Detect language Example error:  RuntimeError: stft requires the return_complex parameter be given for real inputs... python-BaseException

### ISSUE THREAD

**Issue by Domigome** [snakers4/silero-vad#316]
## 🐛 Bug

Trying to run the language (99% accuracy, 95 languages version) sample code provide in https://github.com/snakers4/silero-vad/wiki/Other-Models throws RuntimeError "stft requires the return_complex parameter be given for real inputs...."

## To Reproduce

1. Get the code sample to detect languages provide here: https://github.com/snakers4/silero-vad/wiki/Other-Models
2. Set the environment (information below)
3. Run code.

Traceback (most recent call last):
  File "C:\Users\*/.cache\torch\hub\snakers4_silero-vad_master\utils_vad.py", line 117, in __call__
    outs = self.model(inputs)
  File "C:\Users\*\Documents\Pycharm_HanziToPinyin\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/number_vad_model.py", line 16, in forward
  def forward(self: __torch__.models.number_vad_model.Net_convertable,
    x: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
    x0 = (self.feature_extractor).forward(x, )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x1 = (self.adaptive_normalization).forward(x0, )
    x2 = (self.encoder).forward(x1, )
  File "code/__torch__/models/number_vad_model.py", line 41, in forward
    _4 = self.n_fft
    _5 = self.win_length
    stft_sample = __torch__.torch.functional.stft(wav, _4, self.hop_length, _5, None, True, "reflect", False, None, None, )
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    mag, phase, = _2(stft_sample, 1., )
    if torch.eq(self.mode, "mag"):
  File "code/__torch__/torch/functional.py", line 21, in stft
  else:
    input0 = input
  _2 = torch.stft(input0, n_fft, hop_length, win_length, window, normalized, onesided, return_complex)
       ~~~~~~~~~~ <--- HERE
  return _2
Traceback of TorchScript, original code (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/functional.py", line 515, in stft
        input = F.pad(input.view(extended_shape), (pad, pad), pad_mode)
        input = input.view(input.shape[-signal_dim:])
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
           ~~~~~~~~ <--- HERE
                    normalized, onesided, return_complex)
RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.
python-BaseException

## Expected behavior

Complete execution of code.

## Environment

Please copy and paste the output from this 
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 2.0.0+cpu
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
 - Build command you used (if compiling from source):
 - Python version: 3.9
 - CUDA/cuDNN version: (using cpu at the moment)
 - GPU models and configuration: (using cpu at the moment)
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by snakers4** [comment]
Hi,

We did not update this model for some time, since it was not very popular.

I believe this error started occuring when pytorch released `1.10`. 

We do not really have plans to maintain these models since we decided to focus on the vad, so probably trying older pytorch versions is the only option.
