### ISSUE TITLE
How to use GPU(onnxruntime-gpu) for VAD inference?

### ISSUE THREAD

**Issue by willnufe** [snakers4/silero-vad#321]
## ❓ Questions and Help

I'm trying to run the silero_vad.onnx model that runs fine on CPU[onnxruntime==1.13.1] but fails on GPU/Cuda [onnxruntime-gpu==1.13.1] with the following error:

![20230423-141831](https://user-images.githubusercontent.com/53147925/233823303-074c291f-46a0-4986-8603-641d49bc3907.jpg)

**Comment by sty1992928** [comment]
may I ask how you solve this problem
