### ISSUE TITLE
Long duration causing memory leaks

### ISSUE THREAD

**Issue by eypklyc** [snakers4/silero-vad#356]
Hi,

I'm using Silero VAD to catch speeches in a long audio records.  When using `get_speech_timestamps` function it's causing memory leak. Eventually the process consuming all memory and starting to write swap. Any advice to prevent this apart from cutting the samples multiple pieces?

https://github.com/snakers4/silero-vad/blob/563106ef8cfac329c8be5f9c5051cd365195aff9/utils_vad.py#L267

Just for information using reset states solving the problem but making predictions less accurate...

**Comment by snakers4** [comment]
Does this help?
https://github.com/snakers4/silero-vad/issues/2#issuecomment-1050968656

> long audio record

How long? How much memory is used for audios of which size?
You can consider trying the streaming interface if your audio is very long or "eternal".

> Any advice to prevent this apart from cutting the samples multiple pieces?
> Just for information using reset states solving the problem but making predictions less accurate ...

Cutting audio into 5-15m long segments should not harm the overall quality very much.
Resetting states forgets some context, but it should be negligible compared to the overall length of audio.

**Comment by eypklyc** [comment]
Sorry for the late reply. Yes that helped very well, disabling the gradients solved the leakage

`torch.set_grad_enabled(False)`

Thank you for the support..

**Comment by EarningsCall** [comment]
> Sorry for the late reply. Yes that helped very well, disabling the gradients solved the leakage
> 
> `torch.set_grad_enabled(False)`
> 
> Thank you for the support..

I was having same issue with memory leak.  This seems to have fixed it for me as well.  THanks!

**Comment by EarningsCall** [comment]
> > Sorry for the late reply. Yes that helped very well, disabling the gradients solved the leakage
> > `torch.set_grad_enabled(False)`
> > Thank you for the support..
> 
> I was having same issue with memory leak. This seems to have fixed it for me as well. THanks!

Any idea why this works?
