### ISSUE TITLE
Bug report - Regression of VAD quality between 3.1 and 4.0 (speech detected on perfect silence)

### ISSUE THREAD

**Issue by Jeronymous** [snakers4/silero-vad#396]
## 🐛 Bug

On some audio, the quality of the VAD is reallly worse in the latest version v4.0, compared to what it was in v3.1

More precisely, v4.0 detects speech on "quasi perfect" silent period:
![image](https://github.com/snakers4/silero-vad/assets/22522728/89ca75aa-36c9-4da6-be04-88596f4d9cd0)
* left: v4.0
* right: v3.1

Another user reports the same experience (and spotted v3 to me): https://github.com/linto-ai/whisper-timestamped/issues/74#issuecomment-1817482101

Also, I have troubles to revert to v3.1. See comment here: https://github.com/linto-ai/whisper-timestamped/pull/142#discussion_r1398256438
Maybe I missed something to handle versioning with silero-vad.
Any help on this PR would be very much appreciated.

## To Reproduce

Audio to reproduce : https://github.com/linto-ai/whisper-timestamped/files/11220341/jon.zip

**Comment by snakers4** [comment]
It is a known issue with near zero signals.
This is not a bug, this is a feature (tm).

The newer VAD tries to suppress spurious activations with subtle speech in the background.
We are still thinking on how to fix this if possible at all.

Because suppressing some noise in the background and working on perfectly silent audios are mutually exclusive. In any case post-processing hyper-parameters should be tuned for each domain. Maybe a VAD should have a flag.

**Comment by snakers4** [comment]
Yeah, looks like "perfect" silence:

![image](https://github.com/snakers4/silero-vad/assets/12515440/6772ee39-141d-4c12-b56d-32596376c00e)

**Comment by lixikun** [comment]
> To be solved with a V5 release

Great job!

**Comment by trivikramak** [comment]
Any updates on this?

**Comment by DanyPell** [comment]
Pumped for next version of silero_vad.onnx!

**Comment by yuGAN6** [comment]
> Since the noise is really near-zero, could this be prevented by a preprocessing filter cutting long parts below a set threshold, or -20dB below the average RMS?

you're right. I tried compute RMS per frame and set a threshold of RMS*1000 < 10 and it works well.

**Comment by x86Gr** [comment]
> > Since the noise is really near-zero, could this be prevented by a preprocessing filter cutting long parts below a set threshold, or -20dB below the average RMS?
> 
> you're right. I tried compute RMS per frame and set a threshold of RMS*1000 < 10 and it works well.

Good. With frame you mean the 512/1024/1536 samples?

**Comment by snakers4** [comment]
The new VAD version was released just now - https://github.com/snakers4/silero-vad/issues/2#issuecomment-2195433115

It was designed with this issue in mind and performance on edge cases like thhis data was significantly improved - https://github.com/snakers4/silero-vad/wiki/Quality-Metrics

Can you please re-run your tests and if the issue persists - please open a new issue
