### ISSUE TITLE
Bug report - [`AttributeError in torchaudio: 'list_available_backends' missing in video processing application`]

### ISSUE THREAD

**Issue by lachlanchen** [snakers4/silero-vad#422]
EDIT:  I updated this as Python suggested and it works now. 

```
# .cache/torch/hub/snakers4_silero-vad_master/utils_vad.py

# if 'sox' in torchaudio.list_available_backends():
if 'sox' in torchaudio.list_audio_backends():
```
## 🐛 Bug

Encountered an `AttributeError` when attempting to use `torchaudio` within a video processing application. The application expects the function `list_available_backends` to be available in `torchaudio`, but instead, an error suggests that this attribute does not exist. The error message hints at possibly using `list_audio_backends` as an alternative, indicating a potential discrepancy in the `torchaudio` API or documentation.

## To Reproduce

The error occurred in the context of running a custom video processing script, specifically at the point where `read_audio` function attempts to invoke `torchaudio.list_available_backends()`.

### Steps to reproduce the behavior:

1. Execute a video processing script that involves audio processing with `torchaudio`.
2. The script fails when it reaches the part where `torchaudio.list_available_backends()` is called.
3. An `AttributeError` is thrown, indicating the absence of the `list_available_backends` attribute.

### Error Message:
```
AttributeError: module 'torchaudio' has no attribute 'list_available_backends'. Did you mean: 'list_audio_backends'?
```

## Expected behavior

I expected `torchaudio` to provide a `list_available_backends` function or for the code and documentation to accurately reference the methods available for listing audio backends.

## Environment

- **Operating System**: Linux (Ubuntu), Kernel Version 5.15.0-94-generic
- **Python Version**: 3.12.1
- **Installation Method**: Conda
- **Environment Details**:

## Additional context

This issue has disrupted a video processing project by hindering its ability to process audio data effectively. Clarification on the correct usage of backend listing functions in `torchaudio` or updates to ensure such functionality aligns with the current version of the library would be greatly appreciated.

**Comment by snakers4** [comment]
@lachlanchen 
Please check now
