### ISSUE TITLE
Bug report — Incorrectly Detects Blowing into Mic as Voice

### ISSUE THREAD

**Issue by s1lviu** [snakers4/silero-vad#430]
The Silero Voice Activity Detection (VAD) model incorrectly classifies the sound of blowing directly into the microphone as human speech. This issue persists across various blowing intensities, from soft to strong. The expected behavior is for the VAD to recognize these non-speech, noise-like sounds as non-voice activity.

Reproduction Steps

**Web Application Test:**

- Navigate to the web-based VAD tool at https://www.vad.ricky0123.com/.
- Use the tool to record the sound of blowing into the microphone.
- Observe the VAD output.

**C++ Example Test:**

- Clone the Silero VAD repository from https://github.com/snakers4/silero-vad/tree/master/examples/cpp.
- Compile and run the C++ example according to the provided instructions.
- Input audio by blowing into the microphone.
- Observe the VAD output.

**Expected Behavior**
The VAD should classify the blowing sounds as non-voice activity, distinguishing them from human speech.

**Actual Behavior**
The VAD system classifies the blowing sounds as voice activity, indicating a false positive in voice detection.

**Comment by DanyPell** [comment]
Do you have the probability number?

**Comment by lionsheep0724** [comment]
same here.  ringback tone detected as voice with 94% of probability.

**Comment by snakers4** [comment]
The new VAD version was released just now - https://github.com/snakers4/silero-vad/issues/2#issuecomment-2195433115

It was designed with this issue in mind and performance on noise-only data was significantly improved - https://github.com/snakers4/silero-vad/wiki/Quality-Metrics

Can you please re-run your and tests and if the issue persists - please open a new issue
