### ISSUE TITLE
Bug report - Warnings about Unused Initializers

### ISSUE THREAD

**Issue by lox** [snakers4/silero-vad#445]
## 🐛 Bug

When using onnx runtime in node.js, there are warnings when loading the model:

```
[0;93m2024-03-03 21:57:12.462000 [W:onnxruntime:, graph.cc:3593 CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
```

Is the an issue with the model, or is this an `onnxruntime` issue?

**Comment by snakers4** [comment]
Which `onnx-runtime` version is it?
Does the model work as intended?

**Comment by lox** [comment]
`onnxruntime-node` 1.14.0. 

Yup, the model works well. Discovered via https://github.com/ricky0123/vad/issues/88, but I can reproduce just by loading the model with `onnxruntime-node`.

**Comment by snakers4** [comment]
Let's pin it and check with a new model when it gets released.
Looks like some onnx-runtime quirk.

**Comment by JUiscoming** [comment]
if you don't want to see this message, just add this command,
`onnxruntime.set_default_logger_severity(3)`
it will suppress warning message.

**Comment by snakers4** [comment]
The new VAD version was released just now - https://github.com/snakers4/silero-vad/issues/2#issuecomment-2195433115

It was packed into ONNX with opset 16

It the issue still persists please open another issue
