### ISSUE TITLE
Compile silero-vad-onnx.cpp with MSVC 2022

### ISSUE THREAD

**Issue by skyer9** [snakers4/silero-vad#458]
to compile silero-vad-onnx.cpp with MSVC 2022 in VSCode,
i needed to add code below.

```cpp
#pragma comment(lib, "onnxruntime.lib")
```

for information to someone who do what i did.

**Comment by snakers4** [comment]
Maybe it is worth adding it to readme in the examples folder?

**Comment by skyer9** [comment]
Yes, it made me spend too many time.

**Comment by snakers4** [comment]
Can you please add a PR?

**Comment by skyer9** [comment]
sorry.
i started using MSVC today, before i always used gcc.

in MSVC, using pragma is very common.

sorry.
