### ISSUE TITLE
How to export an ONNX with opset version = 13?

### ISSUE THREAD

**Issue by joyyang1215** [snakers4/silero-vad#459]
How to export an ONNX with opset version = 13? Currently, the silero_vad.onnx is opset version = 16.
Could you tell me how to get other opset version of the ONNX model?
Thanks

**Comment by snakers4** [comment]
While the new release is fresh, we are able to export with certain other opsets.
If this is necessary, please provide the necessary opsets and some reasoning.

**Comment by snakers4** [comment]
If this becomes relevant, please open a new issue.

**Comment by letranhuy2612** [comment]
I would like to downgrade to opset versions lower than 15 because, when deploying the model to Triton, the current Kubernetes setup only supports up to opset 15.This is the error I receive.Thanks
```python
| silero_vad | 1 | UNAVAILABLE: Internal: onnx runtime error 1: Load model from /tmp/folderH4ekFf/1/model.onnx failed:/workspace/onnxruntime/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::__cxx11::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 16 is |
| | | under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 15. |
```

**Comment by snakers4** [comment]
15 for Kubernetes and Triton.
13 for - ?
Are there any other opsets necessary?

**Comment by letranhuy2612** [comment]
I would like to downgrade to opset versions lower than 15 not necessarily 13.Thanks

**Comment by letranhuy2612** [comment]
Could you tell me how to get other opset version of the ONNX model? Thanks

**Comment by snakers4** [comment]
https://github.com/snakers4/silero-vad/pull/573

We added a 16 kHz only ONNX model that was exported with opset 15.
Turns out the tool we were using to package all of the models was internally overriding the opset value and exporting with 16.
Opset 16 has support of if-statements, unlike earlier ones.
If this model would not work for you, please create another issue.
