### ISSUE TITLE
Bug report - [installation] Cannot import name 'get_number_ts' from 'utils_vad'

### ISSUE THREAD

**Issue by hungiito** [snakers4/silero-vad#473]
## 🐛 Bug

I encounter this error when loading model with ref `:v5.0`. When removing `:v5.0`, it works normally

```bash
ImportError: cannot import name 'get_number_ts' from 'utils_vad' (/Users/hunguyen/.cache/torch/hub/snakers4_silero-vad_v5.0/utils_vad.py)
```

## To Reproduce

```
torch.hub.load(
    repo_or_dir="snakers4/silero-vad:v5.0",
    model="silero_vad",
    force_reload=True,
    onnx=True,
    force_onnx_cpu=False,
)
```
## Environment

 - PyTorch Version (e.g., 1.0): 2.3.1
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): `poetry`
 - Python version: `3.10.13`
 - CUDA/cuDNN version: None

**Comment by snakers4** [comment]
Please check now

**Comment by snakers4** [comment]
Since the tag is fixed, will close this one.
Previous version support will be fixed here 
https://github.com/snakers4/silero-vad/issues/474
