### ISSUE TITLE
Bug report - Error in cpp example when using v5 onnx model

### ISSUE THREAD

**Issue by matt1398** [snakers4/silero-vad#477]
## 🐛 Bug

Have a Error in cpp example, when using v5 onnx model, showing:

[W:onnxruntime:, graph.cc:3494 CleanUnusedInitializersAndNodeArgs] Removing initializer 'If_0_else_branch__Inline_0__/decoder/Slice_4_output_0'. It is not used by any node and should be removed from the mode

terminate called after throwing an instance of 'Ort::Exception'
  what():  Invalid Feed Input Name:h
[1]    961551 IOT instruction (core dumped)  ./test

If I change the model to v4, it works well.

**Comment by snakers4** [comment]
A community PR to update the example for a new model would be appreciated.

**Comment by filtercodes** [comment]
> A community PR to update the example for a new model would be appreciated.

Just added it

**Comment by snakers4** [comment]
Many thanks!
