### ISSUE TITLE
Onnx model is not working in v4.0stable

### ISSUE THREAD

**Issue by lokesh-vr-17773** [snakers4/silero-vad#491]
Change in [v4.0stable fx](https://github.com/snakers4/silero-vad/commit/ac128b3c559325239fdf28415368dc06492bcfb7) broke onnx initialization in v4.0stable branch

The `force_onnx_cpu` flag is required for `OnnxWrapper`, as it relies on this flag to assign providers. If this flag is not provided, no providers will be assigned to `InferenceSession`, resulting in the error below:

```python
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```

**Comment by adamnsandle** [comment]
Thanks, fixed it in a recent commit https://github.com/snakers4/silero-vad/commit/915dd3d639b8333a52e001af095f87c5b7f1e0ac
Moved tag v4.0

**Comment by snakers4** [comment]
@lokesh-vr-17773

**Comment by lokesh-vr-17773** [comment]
@adamnsandle Thanks for the quick fix. Just a kind request: please don't move the tags. Instead, we can bump the minor version or patch version, whichever is applicable. Moving tags might create confusion.

cc: @snakers4

**Comment by lokesh-vr-17773** [comment]
@adamnsandle Thanks for the quick fix. Just a kind request: please don't move the tags. Instead, we can bump the minor version or patch version, whichever is applicable. Moving tags might create confusion.

cc: @snakers4

**Comment by snakers4** [comment]
> Thanks for the quick fix. Just a kind request: please don't move the tags. Instead, we can bump the minor version or patch version, whichever is applicable. Moving tags might create confusion.

We will keep all tag names the same, but when fixing bugs we may update the tags so that they will point to the newer fixed versions.
