### ISSUE TITLE
Help. Load model from silero_vad.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by NathanJHLee** [snakers4/silero-vad#495]
## ❓ Questions and Help

We have a [wiki](https://github.com/snakers4/silero-models/wiki) available for our users. Please make sure you have checked it out first.

Hi snakers4.
I tried your new VAD version to run.
But it seem same error as bleow.

terminate called after throwing an instance of 'Ort::Exception'
what(): Load model from silero_vad.onnx failed:Protobuf parsing failed.
Aborted (core dumped)

I followed your instruction.
My env is

docker gcc:12.2.0-bullseye

and I modified some line
//std::wstring path = L"silero_vad.onnx";
std::string path = "silero_vad.onnx";

std::wstring -> std::string

$du -hs silero_vad.onnx
260K silero_vad.onnx

please check my problem.
Thank you.

**Comment by NathanJHLee** [comment]
I asked it before release v5 vad.

https://github.com/snakers4/silero-vad/issues/453

**Comment by snakers4** [comment]
Hi, the only idea that I have is that the file is somehow corrupted on download.
You can check the md5sum of the ONNX file

```
ad78afa8b67a4f24c1201d7dd2f65bb1 silero_vad.onnx
```

**Comment by NathanJHLee** [comment]
asr@809b1e96db7b:~/silero-vad/examples/cpp$ md5sum silero_vad.onnx
b
**f5e8259c8beafe5ab5fb4dc1d0b2349  silero_vad.onnx**

I got different hash value. Where can i find newer onnx model? any url?

**Comment by snakers4** [comment]
The model is in the repo

**Comment by NathanJHLee** [comment]
Thank you for ur help!
I got a right onnx model and it works fine for me.
Thanks a lot!!
