### ISSUE TITLE
ONNX files for "micro" & "micro_8k" models are identical

### ISSUE THREAD

**Issue by 0xEb0** [snakers4/silero-vad#50]
🙏

**Comment by snakers4** [comment]
@adamnsandle 
can you please check
size is the same for sure

**Comment by adamnsandle** [comment]
uploaded fixed model version

**Comment by snakers4** [comment]
@0xEb0 

https://github.com/snakers4/silero-vad/pull/53
please check that everything works

**Comment by 0xEb0** [comment]
it's all good, thx
