### ISSUE TITLE
Csharp example

### ISSUE THREAD

**Issue by nganju98** [snakers4/silero-vad#508]
Did you guys have a language party and forget to invite c sharp?  I've added a c sharp example using your latest v5 onnx model in the examples directory.

On behalf of Bill Gates and all the dotnet community, thanks for making this excellent project.  Honored to contribute back.  

Also thanks to yuguanqin whose java example I copied.

**Comment by snakers4** [comment]
Many thanks for you contribution!

**Comment by snakers4** [comment]
We have at least in theory examples for the following languages:

- cpp
- c#
- go
- java
- python
- rust

For python we have a `pip` package (which is not ideal due to torchaudio backend situation, but we cannot use conda for other, non-technical reasons) now.

I wonder if any of these languages have widely adopted package managers like `pip`.

**Comment by nganju98** [comment]
Yes they all have widely adopted package managers. Before making packages you need an understanding of what people are using it for and hence the right interface. For example both the Java and csharp example only accept a file path of a wave file. But I'd wager your recent popularity is coming from real time voice applications / AI assistants. Deployable packages should cover those use cases, else you're better off letting people clone the repo.On Jul 22, 2024, at 1:07 AM, Alexander Veysov ***@***.***> wrote:﻿
We have at least in theory examples for the following languages:

cpp
c#
go
java
python
rust

For python we have a pip package (which is not ideal due to torchaudio backend situation, but we cannot use conda for other, non-technical reasons) now.
I wonder if any of these languages have widely adopted package managers like pip.

**Comment by snakers4** [comment]
Probably you are right.
In any case publicly we provide only barebones streaming examples, because real applications can get hairy quickly.
Let it remain so for the time being.
