### ISSUE TITLE
Too high onnxruntime version (>= 1.18.0) dependency for v5.1 ?

### ISSUE THREAD

**Issue by JiJiJiang** [snakers4/silero-vad#519]
## ❓ Questions and Help

We have a [wiki](https://github.com/snakers4/silero-models/wiki) available for our users. Please make sure you have checked it out first.

First of all, thank you for your amazing open-source vad toolkit, which is mainly recommended and adopted in our speaker embedding learning toolkit [WeSpeaker](https://github.com/wenet-e2e/wespeaker).

While we used the latest v5.1 version, we found that it depends on onnxruntime >= 1.18.0, which is a little bit unfriendly to some old linux systems, e.g., centos, because of its old GLIBC lib version.
![image](https://github.com/user-attachments/assets/d692092b-8ee9-4eff-8665-e3821dd41a22)
![image](https://github.com/user-attachments/assets/b8356bf9-8a7c-4a21-b1c8-8ce2f6517ee9)

I'm wondering if you guys have noticed this problem and your advice to solve it. Are you planning to support the older onnxruntime versions, e.g., v.1.16, in the next version ?

Thank you for your help!

**Comment by JiJiJiang** [comment]
BTW, could you also put v4 and v3.1 in the pip source?

**Comment by snakers4** [comment]
> BTW, could you also put v4 and v3.1 in the pip source?

Since the pip-package is new (we did not make pip-packages when releasing `v3.1` and `v4`) and the older versions are accessible via git tags, probably building several "new old" pip-package versions is possible, but we want to encourage users to use the new VAD and we really do not want to maintain the older versions of the code in the repo.


> While we used the latest v5.1 version, we found that it depends on onnxruntime >= 1.18.0, which is a little bit unfriendly to some old linux systems, e.g., centos, because of its old GLIBC lib version.

> I'm wondering if you guys have noticed this problem and your advice to solve it. Are you planning to support the older onnxruntime versions, e.g., v.1.16, in the next version ?

There was not much design when choosing the current minimal version. We just took the somewhat fresh version and that is it.
We will check if the current model can be run on `1.16`. If so, we will just change the minimal version required. 

If not, then we will have to think, how to solve this without resorting to having multiple model versions.

**Comment by JiJiJiang** [comment]
Yes, ort ``v1.16.3`` works well with your vad model in my machine.
It is very likely that more older ort version also works. You can check ``v1.11`` for example.

Looking forward to your update!

**Comment by snakers4** [comment]
Please try updating the pip-package now.

**Comment by snakers4** [comment]
We checked that `1.16.1` works with the latest model.
Can you install the VAD from pip (`--no-deps`, `--no-dependencies`) and just manually install the `onnx-runtime` and try?

**Comment by JiJiJiang** [comment]
Yes, my temporary solution is the same as you say. I manually install onnx-runtime ``v1.16.3`` first and then ``pip install silero-vad --no-deps``. Everything works well.
But I think it would be better if you can lower the ort version dependency since ``v1.18`` is not necessary.

Thank you very much for your answer.

**Comment by snakers4** [comment]
We uploaded a new pip-package version that fixes this.
If the error persists, please open a new issue.
Many thanks.

**Comment by JiJiJiang** [comment]
> We uploaded a new pip-package version that fixes this. If the error persists, please open a new issue. Many thanks.

Thank you for update. It also works in my machine now. onnxruntime-1.16.3 and silero-vad-5.1.2 are installed.
