### ISSUE TITLE
Bug report - [Misleading line in the documentation]

### ISSUE THREAD

**Issue by Datasciensyash** [snakers4/silero-vad#523]
### 🐛 Bug

In the **Entire audio inference** section at the link below, there's a comment stating that the audio is split into 31.25 ms pieces:

https://github.com/snakers4/silero-vad/wiki/Examples-and-Dependencies#examples

```python
wav = read_audio('en_example.wav', sampling_rate=SAMPLING_RATE)
# Audio is being split into 31.25 ms long pieces
# so output length equals ceil(input_length * 31.25 / SAMPLING_RATE)
predicts = model.audio_forward(wav, sr=SAMPLING_RATE)
```

However, the next line says that the output length equals `ceil(input_length * 31.25 / SAMPLING_RATE)`, which contradicts the previous statement.

The formula means that each second of the audio contains 31.25 chunks, not that each chunk is 31.25 ms long. The size of each chunk can be inferred from this formula quite easily:

```
1000 / 31.25 = 32.0 ms
```

This is also correct because inside Silero VAD, chunks of size `512` are used for 16 kHz and `256` for 8 kHz:

```
512 / 16000 = 256 / 8000 = 0.032 s = 32.0 ms
```

### Expected Behavior

The documentation should clarify that the chunk size is 32 ms, and each second of the audio contains 31.25 chunks.

**Comment by snakers4** [comment]
Fixed - https://github.com/snakers4/silero-vad/wiki/Examples-and-Dependencies#examples

![image](https://github.com/user-attachments/assets/0532dcbe-b739-4548-833f-31228843d2af)
