### ISSUE TITLE
window_size_samples effects infer speed

### ISSUE THREAD

**Issue by little-duan** [snakers4/silero-vad#532]
when i use v3.1 vad onnx model to process audio file, i found that different window size has different infer speed. the 1024 window size is 2x faster than 512 window size(the whole infer time costs on the same audio file)

however, v5.1 vad model has deprecated the window_size_samples parameter, i think its worth to reuse this parameter.

**Comment by snakers4** [comment]
This makes sense, because in case of larger windows, the VAD is incurred less often.

But the new VAD is heavily simplified and sped up, so it is unlikely that we will return the variable window.
