### ISSUE TITLE
❓ Questions / Help / Support Seeing confidence returned from model significantly drops after the first detection

### ISSUE THREAD

**Issue by kyu-aurelian** [snakers4/silero-vad#538]
## ❓ Questions and Help

I am processing audio bytes in stream and pass these chunks to the model to detect voice, following [this example](https://github.com/snakers4/silero-vad/blob/master/examples/pyaudio-streaming/pyaudio-streaming-examples.ipynb).

I see it correctly detects on the first voice, but after that it seems to get offset and keeps returning very small value for some reason:
```
# speaking
Confidence: 0.8792915519326925
Confidence: 0.8173654739744961
...
# silence
Confidence: 6.792915519326925e-05
Confidence: 7.173654739744961e-05
Confidence: 7.504562381654978e-05
Confidence: 6.430788926081732e-05
Confidence: 5.906085061724298e-05
Confidence: 7.333822577493265e-05

# speaking again
Confidence: 0.002933159237727523
Confidence: 0.0029354665894061327
Confidence: 0.004208957776427269
Confidence: 0.003572070272639394
```

Not sure if I am missing something very obvious..

So seeing `#speaking again` it seems like the model is detecting the sound but with very low confidence for some reason.

**Comment by snakers4** [comment]
From the first glance it seems that this example was not updated for v5, we will take a look

**Comment by kyu-aurelian** [comment]
```
self.model, self.utils = torch.hub.load(
            repo_or_dir="snakers4/silero-vad", model="silero_vad", trust_repo=True
        )
```
I am initializing the model like above, fyi.

btw,
I ran into [this example](https://github.com/snakers4/silero-vad/wiki/Examples-and-Dependencies#dependencies) and adding `self.model.reset_states()` seems to have fixed the issue.

I thought the model was stateless but I guess it's not?

**Comment by snakers4** [comment]
> I thought the model was stateless but I guess it's not?

It isn't, we will update the example.

**Comment by adamnsandle** [comment]
Fixed pyaudio examples
https://github.com/snakers4/silero-vad/pull/539

**Comment by snakers4** [comment]
Files changed:

> [examples/pyaudio-streaming/pyaudio-streaming-examples.ipynb](https://github.com/snakers4/silero-vad/pull/539/files#diff-5b167bbfdeaf9ae26264c5da30910a9655b20af8a66445710ff0e426b58d6d12)

Your url

> https://github.com/snakers4/silero-vad/blob/master/examples/pyaudio-streaming/pyaudio-streaming-examples.ipynb


`examples/pyaudio-streaming/pyaudio-streaming-examples.ipynb` looks the same
