### ISSUE TITLE
[PYTHON] Problems running the ONNX model with CUDAExecutionProvider

### ISSUE THREAD

**Issue by eliran-fm** [snakers4/silero-vad#554]
## ❓ Questions and Help

I'm getting the following error when loading both V4 and V5 ONNX models, while indeed receiving degraded performance:
`2024-10-14 13:15:33.600827068 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 1 Memcpy nodes are added to the graph spox_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.`

Running with `onnxruntime-gpu==1.19.2`

Is this expected?

**Comment by snakers4** [comment]
The probable culprit are 1D convolutions, which sometimes still may be poorly supported

**Comment by eliran-fm** [comment]
I see, thanks!

**Comment by eliran-fm** [comment]
Model is not intended to run on GPU to begin with
