### ISSUE TITLE
How to use Silero VAD in iOS and how to convert the Onnx to CoreMLmodel

### ISSUE THREAD

**Issue by Kamalesh7605** [snakers4/silero-vad#555]
Hi everyone, I'm working on integrating Voice Activity Detection (VAD) technology using the Silero model in my iOS app. I would appreciate any guidance on how to implement the Silero model in an iOS environment, including best practices and relevant resources. Additionally, I need assistance with converting the ONNX model to a Core ML model. Any help would be greatly appreciated!

**Comment by snakers4** [comment]
Hi,

> Silero model in an iOS environment

Probably using ONNX runtime is the easiest option.

> converting the ONNX model to a Core ML model

Typically, such things are what we do commercially for companies for a fee.
