### ISSUE TITLE
After release of silero-mini, colab examples became outdated

### ISSUE THREAD

**Issue by narekvslife** [snakers4/silero-vad#56]
After the release of silero-mini, you added a new function to the [utils_vad.py](https://github.com/snakers4/silero-vad/blob/master/utils_vad.py), which made the following piece of code invalid. Raising 'Too many values to unpack' Exception

```python
(get_speech_ts,
 _, read_audio,
 _, _, _) = utils
```

It should be the following instead:

```python
(get_speech_ts,
 _, _,
read_audio,
 _, _, _) = utils
```

This is true for all examples.

**Comment by snakers4** [comment]
@adamnsandle 

plz check

**Comment by adamnsandle** [comment]
Will fix collab examples asap

**Comment by snakers4** [comment]
@narekvslife 
Please check that this solves your problem
https://github.com/snakers4/silero-vad/pull/60

**Comment by narekvslife** [comment]
@snakers4
It does, thank you!
