### ISSUE TITLE
❓ Issue with silero-vad in Song Detection

### ISSUE THREAD

**Issue by Joy-word** [snakers4/silero-vad#565]
## ❓ Questions and Help

I found that when using silero-vad for voice activity detection in vocal songs, it misses most of the high-pitched parts. I'm wondering if this is related to the project's training data? Is there a way to avoid this during the inference stage? Looking forward to your response.

![E631695A-832F-417c-A61C-DE1B9A69B562](https://github.com/user-attachments/assets/5ef8dbb1-076b-4dad-ae06-120928eae976)

**Comment by snakers4** [comment]
Hi,

It is a known problem with songs / very high voices / children's voices / cartoon voices.

As for music per se - we did not have music in the training data. As for children audio recordings they are much more relatively rare compared to adults.

**Comment by Joy-word** [comment]
OK，Thanks for your response.
