### ISSUE TITLE
Bug report - Sometimes due to rounding the speech segment end time can be bigger than audio end time

### ISSUE THREAD

**Issue by qiisziilbash** [snakers4/silero-vad#576]
## 🐛 Bug

Sometimes, due to rounding, the speech segment end_time can be bigger than audio end time; see [this](https://github.com/snakers4/silero-vad/blob/master/src/silero_vad/utils_vad.py#L381) line.

## To Reproduce

Unfortunately, I can't share the audio; but if you have an audio with high probability of speech at the very end and use `return_seconds=True` you may be able to get the bug surfaced.

## Expected behavior
To round the end time down that the segment end time does not exceed the audio time.

**Comment by snakers4** [comment]
https://github.com/snakers4/silero-vad/pull/579

Please open a new issue if the problem persists
