### ISSUE TITLE
Speech Probability Threshold below 0.15 causes negative Inactivity Threshold

### ISSUE THREAD

**Issue by Yohrog** [snakers4/silero-vad#580]
https://github.com/snakers4/silero-vad/blob/cff5eb2980d64e80dca840277528f1a17bb6193c/src/silero_vad/utils_vad.py#L311

Since neg_threshold will be set with a fixed value of `threshold - 0.15` when not given, neg_threshold will be negative for threshold values less than 0.15.

It'd be good to either set it relative with something like `threshold * 0.7` or at least give a warning to the user.

**Comment by snakers4** [comment]
Good catch.

**Comment by adamnsandle** [comment]
Fixed in 
https://github.com/snakers4/silero-vad/pull/581/commits/eaf633ec9d6594544707c6ea21cedcf9558cb1a3
