### ISSUE TITLE
Trrying to build wyoming app using vad lib, via requirements.txt.. onnxruntime lib not found for arm/v7

### ISSUE THREAD

**Issue by sdetweil** [snakers4/silero-vad#583]
repo here https://github.com/sdetweil/wyoming-sonus (like satellite, but embedded with app) 
(uncomment arm/v7 line of script/build_docker)
execute
script/build_docker

latest_version=1.0.0
docker buildx build . -t "rhasspy/wyoming-sonus:$latest_version"  --platform linux/arm/v7 "$@"

requirements.txt
wyoming==1.6.0
zeroconf==0.88.0
pyring-buffer==1.0.0
pysilero-vad==1.0.0
.
.
1 INFO: pip is looking at multiple versions of pysilero-vad to determine which version is compatible with other requirements. This could take a while.
145.2 ERROR: Could not find a version that satisfies the requirement onnxruntime<2,>=1.10.0 (from pysilero-vad) (from versions: none)
146.1 ERROR: No matching distribution found for onnxruntime<2,>=1.10.0

works ok on arm64 and amd64

not using onnxruntime in impliementation anyhow

**Comment by snakers4** [comment]
> pysilero-vad==1.0.0

This is not our pip package.

> not using onnxruntime in impliementation anyhow

If you need some minimal setup, you can just import the PyTorch model directly from the repo.

**Comment by sdetweil** [comment]
thanks for the fast response.. sorry for the interrupt
