### ISSUE TITLE
Comma missing in README.md VAD examples

### ISSUE THREAD

**Issue by ivan339339** [snakers4/silero-vad#62]
After README.md updates VAD example code looks like this:
```
...

(get_speech_ts,
 get_speech_ts_adaptive
 _, read_audio,
 _, _, _) = utils

...
```
So there are missing commas after `get_speech_ts_adaptive` in several snippets.

**Comment by snakers4** [comment]
@adamnsandle

**Comment by snakers4** [comment]
should be fixed by https://github.com/snakers4/silero-vad/pull/63
