### ISSUE TITLE
Bug report - [timestamps overlap]

### ISSUE THREAD

**Issue by shagho** [snakers4/silero-vad#67]
## 🐛 Bug

Hi
I use `get_speech_ts_adaptive()` function in `utils_vad.py` for find speech regions and when i test a audio with Sample Rate of 16000 and bitrate of 256000 and the video length is about 1 minute some time stamps have overlap such as you consider a timestamp. this time stamp end have overlap with the start of next time stamp

## Environment
 - PyTorch Version : 1.8.1
 - OS : ubuntu 20.04
 - How you installed PyTorch :pip
 - Python version:3.8.5
 - CUDA/cuDNN version: no cuda
 - GPU models and configuration:use cpu in 1 thread by default

**Comment by snakers4** [comment]
Hi,

> a audio with Sample Rate of 16000 and bitrate of 256000 and the video length is about 1 minute some time stamps have overlap such as you consider a timestamp. this time stamp end have overlap with the start of next time stamp

Can you please share your audio for us to replicate the error?

**Comment by shagho** [comment]
it's link[https://drive.google.com/file/d/13AP_xqwhjYpTeTqs0aTnYhoV8kvM7eOO/view?usp=sharing](url)
and the result is below
![Screenshot from 2021-05-12 13-36-35](https://user-images.githubusercontent.com/51749368/117950172-296cec00-b328-11eb-8f23-3da0f7c2ac2b.png)

**Comment by snakers4** [comment]
@adamnsandle 
looks like a bug

**Comment by shagho** [comment]
I think your budy is sleep :))))

**Comment by adamnsandle** [comment]
fixed this issue!

**Comment by snakers4** [comment]
@shagho 
Pls check that this helps with your case

**Comment by shagho** [comment]
thank you bro
it's solved!
