### ISSUE TITLE
NameError: name 'pd' is not defined

### ISSUE THREAD

**Issue by Gorodecki** [snakers4/silero-vad#79]
When i run this code
`speech_timestamps = get_speech_ts_adaptive(wav, model, visualize_probs=True)`
this error:
![image](https://user-images.githubusercontent.com/60197702/124263777-5b3a4c00-db3c-11eb-8d00-b5e24199dccd.png)

May be add lines `import pandas as pd` above this string?
https://github.com/snakers4/silero-vad/blob/24e0d408abeb83bc8180603b418d453a9248fa38/utils_vad.py#L153

**Comment by snakers4** [comment]
I guess you were pointing a line in a different function, not `get_speech_ts_adaptive` but `get_speech_ts`.

Anyway:

https://github.com/snakers4/silero-vad/commit/588e459a00bf60b5a032f6ff42209340234ad996

Try now

**Comment by Gorodecki** [comment]
Thanks!
